theme = "thom"

[editor]
color-modes = true
line-number = "relative"
true-color = true
mouse = false
idle-timeout = 0 # Time for auto-completion to pop-up

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "-"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
select = "underline"
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[editor.indent-guides]
render = true
character = "|"

[keys.normal]
"\\" = "command_palette"
C-s = ":wq"
# "space" = {
#   "space" = ":wa", 
#   "c" = ":buffer-close", 
#   "q" = ":q", 
#   "Q" = ":qa!", 
#   "z" = [":w", "suspend"]
# }
"space" = {"space" = ":wa", "c" = ":buffer-close", "q" = ":q", "Q" = ":qa!", "z" = [":w", "suspend"]}
X = "extend_line_above"
D = "delete_char_backward"